= CookieCutter Python Package Test
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Very Relevant Status Badges
https://github.com/JonasPammer/cookiecutter-pypackage-test/actions/workflows/ci.yml[image:https://github.com/JonasPammer/cookiecutter-pypackage-test/actions/workflows/ci.yml/badge.svg[CI Status]]
https://github.com/JonasPammer/cookiecutter-pypackage-test/actions/workflows/codeql-analysis.yml[image:https://github.com/JonasPammer/cookiecutter-pypackage-test/actions/workflows/codeql-analysis.yml/badge.svg[CodeQL Status]]
image:https://img.shields.io/pypi/pyversions/test_application.svg[Python Versions]


This project is just an example showcase of my https://github.com/JonasPammer/cookiecutter-pypackage project.


toc::[]

== Features

...


== System Requirements

* Python 3.7 / PyPy 3.7 or above

== Installing

This package is available at https://pypi.org/project/test_application[PyPi].

I recommend you to install using https://github.com/pypa/pipx[pipx] -
a tool that helps installing and running end-user applications written in Python
without worrying about any virtualenv magic:

----
$ pipx install test_application
----

But you can of course also install it using normal pip or in your virtual environment:

----
$ python3 -m pip install test_application
----


== Usage

[subs="quotes"]
----
$ test_application *[--help]*
----

// ...


== Extra: Run using Docker
https://github.com/JonasPammer/cookiecutter-pypackage-test/actions/workflows/docker.yml[image:https://github.com/JonasPammer/cookiecutter-pypackage-test/actions/workflows/docker.yml/badge.svg[Docker Workflow Status]]

This Project also offers a best-practiced Dockerfile to run this package in an ensured-to-be-working environment:

Details in link:README_DOCKER.adoc[README_DOCKER].


[[development]]
== 📝 Development
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]
https://results.pre-commit.ci/latest/github/JonasPammer/cookiecutter-pypackage-test/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/cookiecutter-pypackage-test/master.svg[pre-commit.ci status]]
https://github.com/psf/black[image:https://img.shields.io/badge/code%20style-black-000000.svg[code style: black]]
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]

include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]
https://open.vscode.dev/JonasPammer/cookiecutter-pypackage-test[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]

include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/cookiecutter-pypackage-test/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/cookiecutter-pypackage-test/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
