---
name: "\U0001F41B Bug Report"
description: "Report an error you encountered."
title: "[Bug]: "
labels: ["kind/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear description of what the bug is about (I was doing ... I ran ... I expected ... I got ...).
    validations:
      required: true
  - type: textarea
    id: what-i-ran
    attributes:
      label: What I ran:
      description: |
        Paste a log of command(s) you ran and test's output, tracebacks, etc, here.
        NOTE: You need to divivde and enquote each block of commands with ``` yourself.
      placeholder: |
        ```
        
        ```
    validations:
      required: false
  - type: textarea
    id: host
    attributes:
      label: Environment Information
      description: Tell us about your Operating System.
      placeholder: |
        Windows 10
        Python 3.7
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package did you run?
    validations:
      required: true
