---
name: Docker Image Scan / Build / README

"on":
  push:
    branches:
      - "**"
      - "!dependabot*"
      - "!pre-commit*"
    tags:
      - "v*"
    paths:
      - ".github/workflows/docker.yml"
      - ".dockerignore"
      - "Dockerfile"
      - "docker_smoke_test.py"
      - "README_DOCKER.adoc"
      # as per .dockerignore:
      - "requirements.txt"
      - "setup.cfg"
      - "setup.py"
      - "LICENSE"
      - "test_application/**"
  pull_request:
    branches:
      - "main"
      - "master"

permissions:
  contents: read

jobs:
  trivy-security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: set up qemu for docker
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2

      - name: Build Dockerfile.
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: .
          push: false
          load: true
          tags: "jonaspammer/cookiecutter-pypackage-test:local"

      - name: Run Trivy vulnerability scanner on built Image.
        uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          image-ref: "jonaspammer/cookiecutter-pypackage-test:local"
          format: table
          exit-code: "1"
          # relevant read: https://pythonspeed.com/articles/docker-security-scanner/
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: set up qemu for docker
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2

      # We've successfully built it, we've successfully statically scanned it,
      # and now we run it
      - name: Run Docker Smoke Test
        run: python3 docker_smoke_test.py

  dockerhub:
    if: github.event_name != 'pull_request'
    needs: [trivy-security, smoke-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      # https://github.com/docker/metadata-action#semver
      - name: Extract Metadata from Git references (used for tagging the Docker image).
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            jonaspammer/cookiecutter-pypackage-test
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: set up qemu for docker
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2

      - name: login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          username: "jonaspammer"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Dockerfile and push.
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
        with:
          context: .
          push: "${{ github.event_name != 'pull_request' }}"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"

  dockerhub-readme:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: setup ruby
        uses: ruby/setup-ruby@6148f408d35df04b0189be5e64c1458377b8ae13 # tag=v1
        with:
          ruby-version: "2.7.0"

      - name: install asciidoctor
        run: gem install --no-document asciidoctor rouge coderay

      - name: Convert README_DOCKER.adoc to README-DOCKER.xml using Asciidoctor.
        run: asciidoctor -b docbook README_DOCKER.adoc

      # https://github.com/pandoc/pandoc-action-example
      - name: Convert README_DOCKER.xml to README.md using Pandoc.
        uses: docker://pandoc/core@sha256:65d98a5fb89867961479c16f4597134517923661aca23ef63843f6b6e623508b
        with:
          args: "-f docbook -t markdown_strict README_DOCKER.xml -o README.md"

      # https://github.com/docker/build-push-action/issues/21
      - name: Sync README.md to DockerHub.
        uses: peter-evans/dockerhub-description@202973a37c8a723405c0c5f0a71b6d99db470dae # v3
        with:
          username: "jonaspammer"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          repository: "jonaspammer/cookiecutter-pypackage-test"
          short-description: ${{ github.event.repository.description }}
