---
name: build self-contained README
permissions:
  pages: write
  contents: write
"on":
  push:
    paths:
      - ".github/workflows/gh-pages.yml"
      - "CHANGELOG.adoc"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.adoc"
      - "DEVELOPMENT.adoc"
      - "LICENSE"
      - "README.orig.adoc"

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"

      - name: install asciidoctor and other relevant ruby gems
        run: gem install --no-document asciidoctor asciidoctor-reducer rouge coderay

      - name: Generate README.adoc using ascidoctor-reducer.
        run: asciidoctor-reducer README.orig.adoc -o README.adoc

      - name: install asciidoc
        run: sudo apt-get install -y asciidoc

      - name: generate README.xml from README.adoc using ascidoc
        run: asciidoc -b docbook README.adoc

      - name: Generate README.md from README.xml using pandoc
        uses: docker://pandoc/core:2.18
        with:
          args: "-f docbook -t markdown_strict README.xml -o README.md"

      - name: Commit generated READMEs.
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: reduce README.orig.adoc \n ${{ github.event.head_commit.message }}"
          file_pattern: README.adoc README.md
          disable_globbing: true

      - name: Generate HTML
        run: asciidoctor --backend=html5 --destination-dir docs --out-file index.html README.adoc

      - name: Deploy HTML to GitHub Pages (when branch is master).
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/
        if: github.ref == 'refs/heads/master'
